# Generated by Django 4.2 on 2023-06-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_num", models.TextField(blank=True, max_length=100, null=True)),
                (
                    "farm_name",
                    models.CharField(default="None", max_length=100, null=True),
                ),
                ("lat", models.TextField(blank=True, max_length=100, null=True)),
                ("long", models.TextField(blank=True, max_length=100, null=True)),
                ("distance", models.TextField(blank=True, max_length=100, null=True)),
                ("result", models.TextField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
